USE SEARCH_SCHEMA;

CREATE TABLE SEARCH(
    ID_SEARCH BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_AVAILABILITY BIGINT,
    ID_CLIENT BIGINT,
    SERVICE_ID BIGINT,
    RATING BIGINT,
    PRICE FLOAT,
    USER_ID,

);

CREATE TABLE SERVICE(
    ID_SERVICE BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_SEARCH BIGINT,
    SERVICE_NAME VARCHAR(255) NOT NULL,
    SERVICE_DESCRIPTION VARCHAR(255) NOT NULL,
    PRICE_PER_HOUR FLOAT NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);

CREATE TABLE RESPONSE(
    ID_RESPONSE BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_HOUSEKEEPER BIGINT,
    ID_SEARCH BIGINT
);

COMMIT;


3)request{
housekeeper profile,
location,
services,
time frame
}

