USE CLIENT_SCHEMA;

CREATE TABLE CLIENTS (
    ID_CLIENT BIGINT PRIMARY KEY,
    ADDRESS VARCHAR(255),
    ID_USER BIGINT
);

CREATE TABLE HOMES (
    HOMES_ID BIGINT AUTO_INCREMENT PRIMARY KEY,
    NUMBER_OF_ROOMS INT,
    NUMBER_OF_WINDOWS INT,
    NUMBER_OF_BATHROOMS INT,
    DIMENSIONS INT,
    HAS_GARDEN BOOLEAN,
    HAS_SWIMMING_POOL BOOLEAN,
    HAS_PETS BOOLEAN,
    OWNER_SMOKES BOOLEAN,
    DATE_ADDED TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    ID_ADDRESS BIGINT,
    ID_CLIENT BIGINT
);

CREATE TABLE ADDRESSES (
    ID_ADDRESS BIGINT AUTO_INCREMENT PRIMARY KEY,
    HOME_NUMBER VARCHAR(3) NOT NULL,
    STREET_ADDRESS VARCHAR(255) NOT NULL,
    CITY VARCHAR(100) NOT NULL,
    PROVINCE VARCHAR(100) NOT NULL,
    REGION VARCHAR(100) NOT NULL,
    POSTAL_CODE VARCHAR(20) NOT NULL,
    COUNTRY VARCHAR(100) NOT NULL
);

COMMIT;