USE BOOKING_SCHEMA;

CREATE TABLE BOOKINGS (
    ID_BOOKINGS BIGINT AUTO_INCREMENT PRIMARY KEY,
    BOOKED_DATE DATE NOT NULL,
    START_TIME TIME NOT NULL,
    END_TIME TIME NOT NULL,
    STATUS ENUM('PENDING', 'CONFIRMED', 'COMPLETED', 'CANCELLED') NOT NULL,
    CREATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    UPDATED_AT TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP,
    ID_HOUSEKEEPER BIGINT,
    ID_CLIENT BIGINT
);

COMMIT;