USE EMPLOYEE_SCHEMA;

CREATE TABLE EMPLOYEE(
    ID_EMPLOYEE BIGINT AUTO_INCREMENT PRIMARY KEY,
    ID_USER BIGINT,
    ID_AGENCY BIGINT,
    ID_HOUSEKEEPER BIGINT,
    RATING FLOAT,
    SALARY FLOAT
);

COMMIT;